### ISSUE TITLE
Convert to Typescript Part 2

### ISSUE THREAD

**Issue by bigandy** [bigandy/house-control#2]
Now that [the groundwork is in](https://github.com/bigandy/house-control/pull/1) I would like to continue and utilise more that Typescript can offer.

### TODO
- [ ] Stricter typing rules
- [ ] Apply this https://nextjs.org/learn/excel/typescript/nextjs-types
- [ ] type props
- [ ] turn off implicit any
